### ISSUE TITLE
MyPage 버튼 수정

### ISSUE THREAD

**Issue by SeonHwan-Kim** [Soongsil-Developers/terrace-web#27]
## 문제점
- [ ] 모바일 접속 시 mypage 버튼 이미지 치우침 현상
  ![image](https://user-images.githubusercontent.com/96679633/189511593-67450cf6-7e74-414f-86c8-12bdec182614.png)

**Comment by HI-JIN2** [comment]
버튼 모양 및 위치 변경으로 해당 사항 필요 없음.
